name = "satomatashiki-course"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "satomatashiki-course-db"
database_id = "d2cce4ab-61f5-4323-a10a-726a3d42a6f1"

[env.production]
vars = { }

[[env.production.d1_databases]]
binding = "DB"
database_name = "satomatashiki-course-db"
database_id = "d2cce4ab-61f5-4323-a10a-726a3d42a6f1"
